import { describe, it, expect } from 'vitest';
import { classifyPrAsAi } from './pr-classify';

describe('classifyPrAsAi', () => {
  it('returns false for a normal, well-described PR', () => {
    expect(
      classifyPrAsAi({
        title: 'Fix null pointer in payment handler',
        body: 'This PR resolves the null pointer exception in the payment handler by adding a guard clause. Closes #42.',
      }),
    ).toBe(false);
  });

  it('returns true when title and body are both very short', () => {
    expect(classifyPrAsAi({ title: 'fix bug', body: '' })).toBe(true);
  });

  it('returns true when body contains "generated by" AI keyword', () => {
    expect(
      classifyPrAsAi({
        title: 'Refactor authentication module',
        body: 'This code was generated by ChatGPT and reviewed by the author.',
      }),
    ).toBe(true);
  });

  it('returns true when title contains an AI keyword', () => {
    expect(
      classifyPrAsAi({
        title: 'via AI: add docstrings to all functions',
        body: 'Added JSDoc comments to every exported function.',
      }),
    ).toBe(true);
  });

  it('returns true for copilot keyword in body', () => {
    expect(
      classifyPrAsAi({
        title: 'Improve error messages',
        body: 'Suggestions created with Copilot. Manually verified each change.',
      }),
    ).toBe(true);
  });

  it('returns false when body is null but title is long enough', () => {
    expect(
      classifyPrAsAi({
        title: 'Refactor database connection pool to support read replicas',
        body: null,
      }),
    ).toBe(false);
  });

  it('is case-insensitive for AI keywords', () => {
    expect(
      classifyPrAsAi({
        title: 'Generated-By automation script',
        body: 'Some descriptive body content that is long enough to pass length check.',
      }),
    ).toBe(true);
  });

  it('returns false when body is null and title meets length threshold', () => {
    // title length >= 20 and body null → not flagged
    expect(classifyPrAsAi({ title: 'Add retry logic for flaky tests', body: null })).toBe(false);
  });
});
