import { describe, it, expect, vi, beforeEach } from 'vitest';
import { classifyPrAsAi } from './pr-classify';
import { llmCall } from '@/lib/llm/router';
import { err, ok } from '@/lib/result';

vi.mock('@/lib/llm/router', () => ({
  llmCall: vi.fn(),
}));

describe('classifyPrAsAi', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('LLM classification', () => {
    it('returns true when LLM flags as AI generated', async () => {
      vi.mocked(llmCall).mockResolvedValue(
        ok({ isAiGenerated: true, confidence: 0.9, reason: 'Looks like AI' }),
      );
      const result = await classifyPrAsAi({ title: 'Normal title', body: 'Normal body' });
      expect(result).toBe(true);
      expect(llmCall).toHaveBeenCalledTimes(1);
    });

    it('returns false when LLM flags as genuine', async () => {
      vi.mocked(llmCall).mockResolvedValue(
        ok({ isAiGenerated: false, confidence: 0.9, reason: 'Genuine' }),
      );
      const result = await classifyPrAsAi({ title: 'Normal title', body: 'Normal body' });
      expect(result).toBe(false);
      expect(llmCall).toHaveBeenCalledTimes(1);
    });
  });

  describe('fallback heuristic (when llmCall returns err)', () => {
    beforeEach(() => {
      vi.mocked(llmCall).mockResolvedValue(err('llm_unavailable', 'mock failure'));
    });

    it('returns false for a normal, well-described PR', async () => {
      expect(
        await classifyPrAsAi({
          title: 'Fix null pointer in payment handler',
          body: 'This PR resolves the null pointer exception in the payment handler by adding a guard clause. Closes #42.',
        }),
      ).toBe(false);
    });

    it('returns true when title and body are both very short', async () => {
      expect(await classifyPrAsAi({ title: 'fix bug', body: '' })).toBe(true);
    });

    it('returns true when body contains "generated by" AI keyword', async () => {
      expect(
        await classifyPrAsAi({
          title: 'Refactor authentication module',
          body: 'This code was generated by ChatGPT and reviewed by the author.',
        }),
      ).toBe(true);
    });

    it('returns true when title contains an AI keyword', async () => {
      expect(
        await classifyPrAsAi({
          title: 'via AI: add docstrings to all functions',
          body: 'Added JSDoc comments to every exported function.',
        }),
      ).toBe(true);
    });

    it('returns true for copilot keyword in body', async () => {
      expect(
        await classifyPrAsAi({
          title: 'Improve error messages',
          body: 'Suggestions created with Copilot. Manually verified each change.',
        }),
      ).toBe(true);
    });

    it('returns false when body is null but title is long enough', async () => {
      expect(
        await classifyPrAsAi({
          title: 'Refactor database connection pool to support read replicas',
          body: null,
        }),
      ).toBe(false);
    });

    it('is case-insensitive for AI keywords', async () => {
      expect(
        await classifyPrAsAi({
          title: 'Generated-By automation script',
          body: 'Some descriptive body content that is long enough to pass length check.',
        }),
      ).toBe(true);
    });

    it('returns false when body is null and title meets length threshold', async () => {
      // title length >= 20 and body null → not flagged
      expect(await classifyPrAsAi({ title: 'Add retry logic for flaky tests', body: null })).toBe(
        false,
      );
    });
  });
});
