blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Start a Discussion
    url: https://github.com/Coder-s-OG-s/MergeShip/discussions
    about: Not a bug or feature request? Ask here.
